# Generated by Django 3.1.7 on 2021-02-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0004_auto_20210227_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
